### ISSUE TITLE
Easier way to grab Video ID?

### ISSUE THREAD

**Issue by MachineLearningReefer** [martinopiaggi/summarize#1]
Is it possible to code :

```python
def extract_video_id(url):
    return url[-11:] 
```  
To obtain extract_video_id value as opposed to :
```python
    regex = r'(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})'
    video_id =  re.search(regex, url).group(1)
``` 
I feel like while the above regex works, it's also highly confusing. I am curious why you went the above route if we can safely assume the last 11 characters will always be the video id? Is this not always the case?

This is not an issue, but I did not see any other way to ask you about what led to the decision to do the full regular expression, making a non-capturing group nesting other non-capturing groups. 

Regardless, it works well!

**Comment by MachineLearningReefer** [comment]
```python
def download_youtube_captions(url):
    video_id = url[-11:] 
    transcript_list = **YouTubeTranscriptApi.list_transcripts(video_id)**
``` 

...Would be the new section of code if the last 11 characters rule is always true for youtube videos.

**Comment by MachineLearningReefer** [comment]
I can verify that it does work, should there be a reason you never want to have to look at that regex expression ever again.

**Comment by martinopiaggi** [comment]
Thank you for sharing your simpler approach. I chose that ugly regex to be more robust: more than once, I accidentaly included parameters like 'si' and '&t=' which YouTube includes when the "share button" is used after the video id.

**Comment by Uniqueml** [comment]
Oooooooo that's a good point, it DOES include time stamps sometimes.
